### ISSUE TITLE
Failed to compile. error when building the create-react-app project

### ISSUE THREAD

**Issue by patotoma** [nvh95/react-linkedin-login-oauth2#1]
Hello, I see this error when trying to build create-react-app based project with this library:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/react-linkedin-login-oauth2/node_modules/query-string/index.js:8

Read more here: http://bit.ly/2tRViJ9
```

**Comment by nvh95** [comment]
@patotoma It looks like a problem with `query-string` 6.x
I will update and publish within today. Thanks for reporting.

**Comment by nvh95** [comment]
@patotoma Please run
```
npm install --save react-linkedin-login-oauth2
```
in your project and build again. Please inform me if the problem still persists. Thanks

**Comment by patotoma** [comment]
@nvh95 Problem no longer exists in `1.0.5`, thank you!
