### ISSUE TITLE
At least give option for not doing console.log

### ISSUE THREAD

**Issue by cyberhck** [nvh95/react-linkedin-login-oauth2#11]
https://github.com/nvh95/react-linkedin-login-oauth2/blob/3a912156f27156fc4f69ae6e19ad70f888c89071/src/LinkedInPopUp.js#L16

https://github.com/nvh95/react-linkedin-login-oauth2/blob/3a912156f27156fc4f69ae6e19ad70f888c89071/src/LinkedIn.js#L31

https://github.com/nvh95/react-linkedin-login-oauth2/blob/3a912156f27156fc4f69ae6e19ad70f888c89071/src/LinkedIn.js#L43

Please at least accept a optional props for doing console.log

**Comment by nvh95** [comment]
Thanks for tour feedback. Will do in the next update.

**Comment by praveenkumarrize** [comment]
![image](https://user-images.githubusercontent.com/50015149/60952577-23b3b300-a319-11e9-9d7e-4c5eede3b13c.png)

I am facing this issue after login to linkedin. What should I do.

**Comment by nvh95** [comment]
@praveenkumarrize Can you create another issue and describe the steps to reproduce your issue.
If you can provide source code it would help. Thanks

**Comment by nvh95** [comment]
@cyberhck It is resolved in version `1.0.7`
