### ISSUE TITLE
Release for V 1.1? (Internet Explorer 11 support)

### ISSUE THREAD

**Issue by finnsea** [nvh95/react-linkedin-login-oauth2#12]
Was wanting to know the status for the release of V 1.1 which is set to support IE 11. Any sort of a timeline?

**Comment by nvh95** [comment]
You are trying to use `react-linkedin-login-oauth2` with IE 11, aren't you?
I haven't had a timeline yet. But if there is demand, I can try to release it before 15.08.2019 :)

**Comment by nvh95** [comment]
@finnsea I released version 1.0.7 and it supports IE already.
Please give me feedback after you try it. Much appreciated.

**Comment by finnsea** [comment]
Cool we will give it a try and let you know if we have any issues or
questions.
