### ISSUE TITLE
How to move popup window into the center

### ISSUE THREAD

**Issue by leppid** [nvh95/react-linkedin-login-oauth2#14]
Any solutions?

**Comment by mehdirazajaffri** [comment]
https://github.com/nvh95/react-linkedin-login-oauth2/pull/15

**Comment by leppid** [comment]
@mehdirazajaffri, thanks!

**Comment by nvh95** [comment]
Resolved in 1.0.8. Please `npm install react-linkedin-login-oauth2 --save` to get the latest version.
Thanks.
