### ISSUE TITLE
Issue with scope

### ISSUE THREAD

**Issue by pratiyush2706** [nvh95/react-linkedin-login-oauth2#17]
I haven't defined scope since it is not a required field but it still gives me this error.
`error: "invalid_request"
errorMessage: "You need to pass the "scope" parameter"
from: "Linked In"`

**Comment by nerdmax** [comment]
+1! This is also an issue with the Demo you provided: https://stupefied-goldberg-b44ee5.netlify.com/

![image](https://user-images.githubusercontent.com/18550349/71424956-9d830180-26eb-11ea-93a7-1fd25d662885.png)

**Comment by chocobuckle** [comment]
@pratiyush2706 @nerdmax It seems LinkedIn have changed their API slightly and now require that the scope is explicitly stated. So if you include ```scope="r_liteprofile&r_emailaddress&w_member_social"``` as a prop that should work for you. Those three are the default fields that you can find under 'Auth' > 'Permissions' in your app settings. If you want more than that you need to apply to LinkedIn for access to those - https://docs.microsoft.com/en-us/linkedin/shared/references/v2/profile/full-profile?context=linkedin/consumer/context

**Comment by nerdmax** [comment]
@chocobuckle Thank you so much for the quick response!

**Comment by nvh95** [comment]
@pratiyush2706 @nerdmax Default `scope` is `r_emailaddress` in `1.0.8`. The demo is updated also. 
@chocobuckle Thanks for your explanation.
Feel free to reopen this issue if the problem still persists. Thanks

**Comment by QaimSiddiqui** [comment]
@nvh95 @chocobuckle how to get linkedin user unique id , i get code which is not useful, i want unique linkedin user id
```
<LinkedIn
                      clientId="777d0s26wvou9r"
                      scope="r_liteprofile"
                      onFailure={this.handleLinkedInFailure}
                      onSuccess={this.handleLinkedInSuccess}
                      redirectUri="http://localhost:3000/login/linkedin"
                    >
                      linkedin
                    </LinkedIn>
```
