### ISSUE TITLE
How to get profile data (r_emailaddress 3-legged member permission)

### ISSUE THREAD

**Issue by mathavan161293** [nvh95/react-linkedin-login-oauth2#18]
Could you please update after receiving the code?

handleSuccess = (data) => {
    CODE, 
    ACCESS TOKEN,
    BEARER TOKEN
}

i have an ERROR for 404 in the CORS origin issues..

**Comment by ismailkherbach** [comment]
After asking member permission you will get a code, after that you should make another POST request using that code to get the access token check the Official docs Step 3 : [https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin/context](url)

**Comment by nvh95** [comment]
Please refer to https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin%2Fcontext&tabs=HTTPS#step-3-exchange-authorization-code-for-an-access-token
