### ISSUE TITLE
How to exchange Authorization Code with Access Token

### ISSUE THREAD

**Issue by patotoma** [nvh95/react-linkedin-login-oauth2#2]
I'm trying to implement Linkedin Oauth2 according to this: https://developer.linkedin.com/docs/oauth2.

What I receive using this component onSuccess hook is **Authorization Code** but I need to exchange it with **Access Token** and then send the token to my server.

Making another POST: https://www.linkedin.com/oauth/v2/accessToken is returning CORS error:

```
Failed to load https://www.linkedin.com/oauth/v2/accessToken: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
```

Thank you.

**Comment by nvh95** [comment]
Hey @patotoma 
Are you sure that you add your `redirect_uri` to your app setting
![image](https://user-images.githubusercontent.com/8603085/46269989-f4446e80-c56e-11e8-87eb-64e054670f58.png)
In addition, I don't think that you should put the **Client Secret** in your React App. I think you should send the **Authorization Code** to server and let your server exchange the **Access Token** for you
Let me know if you have any question.

**Comment by patotoma** [comment]
@nvh95 exchanging code with token worked from the server side, thanks.
