### ISSUE TITLE
I'm not able to pass scope for r_liteprofile  and r_emailadress

### ISSUE THREAD

**Issue by sumitmoga** [nvh95/react-linkedin-login-oauth2#21]

**Comment by nvh95** [comment]
@sumitmoga Can you describe your problem more explicitly?
You can always pass scope like this file
https://github.com/nvh95/react-linkedin-login-oauth2/blob/master/demo/src/LinkedInPage.js#L32

**Comment by AkshayDigheGithub** [comment]
pass scope like this  
```
<LinkedIn
                            className="btn btn-block btn-info"
                            clientId={clId}
                            scope="r_liteprofile r_emailaddress"
                            onFailure={this.handleFailure}
                            onSuccess={this.handleSuccess}
                            redirectUri="http://localhost:3000/linkedin"
                       />
```

**Comment by maxlech974** [comment]
> scope="r_liteprofile r_emailaddress"

Hi!
I get the same error than @sumitmoga nothing to do with your solution unfortunatly, any othoer idea?

**Comment by raj-vc** [comment]
scope="r_liteprofile+r_emailaddress"

**Comment by nvh95** [comment]
Please just pass the list delimited by a space.
```
scope="r_liteprofile r_emailaddress"
```
@maxlech974 Can you provide the error message?

**Comment by nvh95** [comment]
I'm closing this issue. Please feel free to comment if this issue still persist
