### ISSUE TITLE
Don't work with multi tenant application

### ISSUE THREAD

**Issue by axeldouglas** [nvh95/react-linkedin-login-oauth2#22]
I'm trying use te component inside a multi tenant application, but Linkedin can accept only an "unique" redirect uri. So when the popup catch the code nothing happen because of uri.
Ex.
Url with linkedin button: http://slug.company.com
Redirect uri: http://company.com/callback

When I receive the code nothing happen (http://company.com/callback/code=**********)

How can I redirect back to the subdomain?

**Comment by jaykrs** [comment]
i am also facing same issue , after authentication successful from pop up , it is not redirecting back to same page from where flow started.

**Comment by nvh95** [comment]
@axeldouglas Can you set your redirect uri with this form http://slug.company.com/callback (same origin with url with linkedin button)?

**Comment by jaykrs** [comment]
Thanks i am able to resolve with callback , happy to help some one if facing same issue.

**Comment by nvh95** [comment]
@jaykrs Can tou share what you did to resolve it?

**Comment by jaykrs** [comment]
this helped me https://github.com/jaykrs/linkedin-react-login , nothing it is simple callback and redirected to https web url .
