### ISSUE TITLE
Could not find a declaration file for module 'react-linkedin-login-oauth2'.

### ISSUE THREAD

**Issue by pradeeptinku** [nvh95/react-linkedin-login-oauth2#24]
I'm working on a reactJs project using Material-UI and there's neither Typescript. nor 'tsconfig.json' file in my project. 
I tried this module 5 days back and it worked fine. But now, I'm getting the below error after the '1.0.8' release.

> Could not find a declaration file for module 'react-linkedin-login-oauth2'. '/Users/pg185136/Desktop/RethinkingUX/Website/BitBucket/rethinkingux/node_modules/react-linkedin-login-oauth2/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-linkedin-login-oauth2` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-linkedin-login-oauth2';`ts(7016)

I've gone thru this [blog](https://blog.atomist.com/declaration-file-fix/) on this issue but as my project is not in typescript, I can't even apply any of these fixes. Lemme know if I'm missing anything.
Any help is much appreciated. 
@YBeck @nvh95 @Songuku95 @jaykrs

**Comment by nvh95** [comment]
@pradeeptinku Can you provide a repository to reproduce? Thanks

**Comment by aLx450** [comment]
I went around it with adding
`//@ts-ignore`
above the import.

The types file does not exist, it seems. You can create your own if you absolutely need it, though. I didn't, so the ignore works just fine.

**Comment by pg185136** [comment]
Yes. @aLx450 It did worked. Thanks for the response.
@nvh95 Thank you.

**Comment by nvh95** [comment]
`react-linkedin-login-oauth2` 2.x alpha is now written in typescript. Do not need to add `//@ts-ignore`
Please give it a try by running:
```
npm i react-linkedin-login-oauth2@alpha
```

See the usage at https://github.com/nvh95/react-linkedin-login-oauth2/blob/a16b68c642cdfea8fd8da102628b69825e03cef2/README.md#L44-L76

**Comment by nvh95** [comment]
`npm i react-linkedin-login-oauth2` version 2 is out with type support.

**Comment by nvh95** [comment]
@all-contributors please add @pradeeptinku for bug
