### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:0)

### ISSUE THREAD

**Issue by marieqg** [nvh95/react-linkedin-login-oauth2#25]
Hello, 
I installed react-linkedin-login-oauth2  and created the button as it was explained. However, 
everytime I get the following error: 

```
./node_modules/react-linkedin-login-oauth2/assets/linkedin.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

My config: 
"react-linkedin-login-oauth2": "^1.0.8",
"node": 12.16.1
 "next": "9.3.6"

I don't have a webpack configured. I think its due to next.js but I'm not sure

Do you have any ideas on how I can fix this? 

Thanks in advance :)

**Comment by shubhamambastha** [comment]
How you fixed this issue? @marieqg
