### ISSUE TITLE
Add @types do use with typescript

### ISSUE THREAD

**Issue by uricbonatti** [nvh95/react-linkedin-login-oauth2#27]

**Comment by nvh95** [comment]
`react-linkedin-login-oauth2` version `2.x` is re-written in typescript.

Please give it a try by running:
```
npm i react-linkedin-login-oauth2@alpha
```

See the usage at https://github.com/nvh95/react-linkedin-login-oauth2/blob/a16b68c642cdfea8fd8da102628b69825e03cef2/README.md#L44-L76

**Comment by nvh95** [comment]
`npm i react-linkedin-login-oauth2` version 2 is out with type support.

**Comment by nvh95** [comment]
@all-contributors please add @uricbonatti for bug
