### ISSUE TITLE
NextJS - Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by phillipDenness** [nvh95/react-linkedin-login-oauth2#30]
Not compatible with server side rendering framework NextJs.
```
./node_modules/react-linkedin-login-oauth2/assets/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules\react-linkedin-login-oauth2\es\LinkedIn.js
```
For reference from Next JS: https://github.com/vercel/next.js/blob/master/errors/css-npm.md

**Comment by nvh95** [comment]
@phillipDenness Hey I will make importing `index.css` file is opt-in. It should be done in 3-5 days. I will let you know after I published the fix

**Comment by nvh95** [comment]
@phillipDenness Sorry for the delay but this issue got fixed in `1.0.9-alpha.0`
You can fix it by running this command
```sh
npm i react-linkedin-login-oauth2@alpha
```
or 
```sh
yarn add react-linkedin-login-oauth2@alpha
```

I will publish latest version to `1.0.9` in a few days. Thank you.

**Comment by nvh95** [comment]
@all-contributors please add @phillipDenness  for bug

**Comment by phillipDenness** [comment]
thank you
