### ISSUE TITLE
Cannot be used with React 17

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [nvh95/react-linkedin-login-oauth2#41]
I'm trying to use package with React 17.0.2, however it requires React 16.x

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: next-flair-front-end@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x" from react-linkedin-login-oauth2@1.0.9
npm ERR! node_modules/react-linkedin-login-oauth2
npm ERR!   react-linkedin-login-oauth2@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/vitalii/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vitalii/.npm/_logs/2021-05-17T19_43_13_791Z-debug.log

**Comment by nagulan23** [comment]
Did u find an alternate?

**Comment by vitalii-bulyzhyn** [comment]
@nagulan23 I sent an PR, but it was never merged. You can fork it and install it to your app from github directly

**Comment by nagulan23** [comment]
Wow thanks :)

**Comment by nvh95** [comment]
@vitalii-bulyzhyn @nagulan23 I just update the package to `1.0.10` to add react 17.x as peerDependencies. Can you try again if it resolve the problem. Thanks for your patience.
```shell
npm i react-linkedin-login-oauth2
```
