### ISSUE TITLE
Is there a way to embed linkedin login and permission granting redirection from codebase? 

### ISSUE THREAD

**Issue by Jyothi-Rajanna** [nvh95/react-linkedin-login-oauth2#46]
I have a requirement to display LinkedIn posts on clients' website. All I need to get is Auth code. By using 'react-linkedin-login-oauth2' package am able to get the 'code''easily by providing linkedin login credentials and allowing permissions, but the client doesn't want to provide login credentials and permission allowing button click on website? Is there a way to embed LinkedIn login and permission granting pages redirection from codebase by hardcoding username and password info using 3 legged Oauth?

**Comment by nvh95** [comment]
Sadly no. I don't think I should ever recommend anyone hard code the password in the client code base.
