### ISSUE TITLE
Security Issue - state was removed and generated randomly , which exposes CSRF attack . 

### ISSUE THREAD

**Issue by donprecious** [nvh95/react-linkedin-login-oauth2#49]
The state was removed and generated randomly, which exposes CSRF attack.  

previously state was an optional field and was entirely removed on this commit https://github.com/nvh95/react-linkedin-login-oauth2/commit/4274b93cbd5512e79d22725961de66a6a2360bd5?short_path=b335630#r58595171  

with the removal, it makes it impossible for the backend server to generate a state for that user and validate it . 

the state should be brought back as optional. since most of us where already passing the state as a prop. which are validated at the backend , generating a random state exposes a security issue .  

Kindly check out linked auth documentation  

https://docs.microsoft.com/en-us/linkedin/shared/authentication/authorization-code-flow?context=linkedin%2Fconsumer%2Fcontext&tabs=HTTPS

**Comment by nvh95** [comment]
I'm closing this issue for now. Please let me know if there is a scenario when CSRF attack might be performed. However, I think it's fair to let users choose their own state, if users don't specify, it will be ramdomly generate for them. This property will be added again in `2.x` (currently in progress #50)
