### ISSUE TITLE
Popup does not close even if the login is successful or user presses cancel button. It redirects me back to origin url without closing the popup.

### ISSUE THREAD

**Issue by faisalur-rehman** [nvh95/react-linkedin-login-oauth2#54]
Popup does not close even if the login is successful or user presses cancel button. It redirects me back to origin url without closing the popup. Here is my code:
```
import React, { useState } from "react";

import { useLinkedIn } from "react-linkedin-login-oauth2";
// You can use provided image shipped by this package or using your own
// import linkedin  from "react-linkedin-login-oauth2";

export default function LinkedInPage() {
  const { linkedInLogin } = useLinkedIn({
    clientId: "{my_client_id}",
    redirectUri: `${window.location.origin}/linkedin`,
    onSuccess: (code) => {
      console.log(code);
    },
    onError: (error) => {
      console.log(error);
    },
  });

  return (
    <img
      onClick={linkedInLogin}
      //   src={linkedin}
      alt="Sign in with Linked In"
      style={{ maxWidth: "180px", cursor: "pointer" }}
    />
  );
}

```

**Comment by nvh95** [comment]
@faisalur-rehman Can you provide some more information like which browser you are using and its version, screenshot or even a reproduce repository?

**Comment by faisalur-rehman** [comment]
I am using Chrome version 95.0.4638.69
Here is the link of the repository : [Link](https://github.com/faisalur-rehman/react-linkedin-facebook-google-signin)
Here is the deployed link of app. [app link](https://react-linkedin-oauth.netlify.app/)
Note: The popup wont close and will redirect in the same window but due to the free hosting on netlify,it will show "Page not found error".

**Comment by faisalur-rehman** [comment]
@nvh95 another issue is that `linkedin` or `{linkedin}` is not exported from `react-linkedin-login-oauth2` which is used in `src` attribute of `<img/>`

**Comment by faisalur-rehman** [comment]
@nvh95 anything?

**Comment by nvh95** [comment]
Hey @faisalur-rehman, in order to make it work, you need to create a route `/linkedin` and it should be `LinkedInCallback`. Since you are using Create React App, I recommend using `react-router-dom` as follow:
```js
import React from 'react';
import { LinkedInCallback } from 'react-linkedin-login-oauth2';

import { BrowserRouter, Route, Switch } from 'react-router-dom';

function Demo() {
  return (
    <BrowserRouter>
      <Route exact path="/linkedin" component={LinkedInCallback} />
    </BrowserRouter>
  );
}
```

Please refer [Usage](https://github.com/nvh95/react-linkedin-login-oauth2#usage) to see how to integrate `react-linkedin-login-oauth2` to your application. You can find a full example [here](https://github.com/nvh95/react-linkedin-login-oauth2-demo/blob/9f95827684314f89c1e5f38374f47ef9cb8da575/src/App.js#L7-L16)
Please let me know if it resolves your problem.

> @nvh95 another issue is that linkedin or {linkedin} is not exported from react-linkedin-login-oauth2 which is used in src attribute of <img/>
That's a mistake in documentation, you can import like this. I updated the README file. Thank you.
```js
import linkedin from "react-linkedin-login-oauth2/assets/linkedin.png";

```

@all-contributors please add @faisalur-rehman for bug

**Comment by faisalur-rehman** [comment]
@nvh95 Yes this resolved the issue. Thanks alot.
```
`Hey @faisalur-rehman, in order to make it work, you need to create a route /linkedin and it should be LinkedInCallback. Since you are using Create React App, I recommend using react-router-dom as follow:

import React from 'react';
import { LinkedInCallback } from 'react-linkedin-login-oauth2';

import { BrowserRouter, Route, Switch } from 'react-router-dom';

function Demo() {
  return (
    <BrowserRouter>
      // Your `linkedin` callback route
      <Route exact path="/linkedin" component={LinkedInCallback} />
      // Other routes
      ...
    </BrowserRouter>
  );
}
Please refer Usage to see how to integrate react-linkedin-login-oauth2 to your application. You can find a full example here
Please let me know if it resolves your problem.
```

**Comment by me-ibad** [comment]
for react router 6 use this one
 <Route exact path='/linkedin' element={<LinkedInCallback />} />

**Comment by hannanel100** [comment]
exact is not supported in react-router v6.

**Comment by saleh1312** [comment]
> for react router 6 use this one <Route exact path='/linkedin' element={} />

<Route exact path='/linkedin' element={ < LinkedInCallback /> } />
and dont forget to add https://localhost:3000/linkedin to your OAuth 2.0 settings in likedin developer app
