### ISSUE TITLE
Having issue with popup

### ISSUE THREAD

**Issue by abhiram5** [nvh95/react-linkedin-login-oauth2#7]
I just tried your react-linkedin-login-oauth2 through npm. I'm able to log in through linked in perfectly but after login, the redirect URL happening in the popup instead of the parent window.

I tried this.
           ``````

                <LinkedIn
                        clientId="xxxxxxxxxxxxxxxx"
                        redirectUri={`${`http://localhost:3004/#/login`}/linkedin`}
                        onFailure={this.handleFailure}
                        onSuccess={this.handleSuccess}
                      >
                       Login with linkedin
                 </LinkedIn>
```
```

**Comment by atrimn** [comment]
same here

**Comment by protolabz** [comment]
I am facing the same problem,
did you get a solution for it?
@abhiram5 & @atrimn

**Comment by jason2li** [comment]
I'm having the same issue

**Comment by PaulAbarnou37** [comment]
This should help you:
https://stackoverflow.com/questions/43209666/react-router-v4-cannot-get-url

Go to your webpack.config.js file :

 ` output: {
    path: path.join(__dirname, outputDirectory),
    filename: 'bundle.js',
    publicPath: '/',  --> ADD THIS
  },` 


  `devServer: {
    historyApiFallback: true, --> ADD THIS
    port: 3000,
    open: true,
    proxy: {
      '/api': 'http://localhost:8080'
    }
  },`

**Comment by dev-svikrant406** [comment]
This doesn't help me...

**Comment by nvh95** [comment]
@abhiram5 @atrimn I belive that you didn't define route for `/linkedin`
Please do it by adding this route somewhere in your application
```
import { Route } from 'react-router-dom';
import { LinkedInPopUp } from 'react-linkedin-login-oauth2';

        ...
         <Route exact path="/linkedin" component={LinkedInPopUp} />
        ...
```

Feel free to reopen this issue if your problem still persists.

**Comment by HarshaV198** [comment]
`componentDidMount(){
    const params = queryString.parse(window.location.search);
    if (params.error) {
      const errorMessage = params.error_description || 'Login failed. Please try again.';
      window.opener && window.opener.postMessage({ error: params.error, state: params.state, errorMessage, from: 'Linked In' }, window.location.origin);
      if (params.error === 'user_cancelled_login') {
        window.close();
      }
    }
    if (params.code) {
      window.opener && window.opener.postMessage({ code: params.code, state: params.state, from: 'Linked In'}, window.location.origin);
    }
    if(params.linkedin_redirect_url) {
      window.location.href = params.linkedin_redirect_url
    }
  }`

put this inside redirected component.
