### ISSUE TITLE
Issue with scope after clicking on linkedin button

### ISSUE THREAD

**Issue by yatrikp** [nvh95/react-linkedin-login-oauth2#8]
Seeing an issue after clicking on the LinkedIn button.

Steps:
1. started the app using "npm start"
2. app started on "localhost:3000"
3. seeing message on the page after clicking on LinkedIn button to login (had logged into the Linkedin on different page)

Message displayed:

"No code
Scope &quot;r_fullprofile&quot; is not authorized for your application"

**Comment by jeromemmiranda** [comment]
@yatrikp I've also experience this. I think it's not a plugin issue. Check your application list of permissions.

![image](https://user-images.githubusercontent.com/10767122/57897315-c48c7180-7886-11e9-83b5-b207ed2bed2e.png)

**Comment by nvh95** [comment]
@yatrikp I guess Linked In remove permission `r_fullprofile` recently. You just need to remove it from `scope` property, or check permissions list like @jeromemmiranda suggests.
Let me know if you still see this problem. Thanks

**Comment by yatrikp** [comment]
works now. thanks a lot for the help!!!
